export const GET_POST_LOADING = "GET_POST_LOADING";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILED = "GET_POST_FAILED";

export const ADD_POST_LOADING = "ADD_POST_LOADING";
export const ADD_POST_FAILED = "ADD_POST_FAILED";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";

export const DELETE_POST_LOADING = "DELETE_POST_LOADING";
export const DELETE_POST_FAILED = "DELETE_POST_FAILED";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

export const GET_POST_BYID_SUCCESS = "GET_POST_BYID_SUCCESS";
export const UPDATE_POST_LOADING = "UPDATE_POST_LOADING";
export const UPDATE_POST_FAILED = "UPDATE_POST_FAILED";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
