export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";


export const GET_USER_ByID_LOADING = "GET_USER_ByID_LOADING";
export const GET_USER_BYID_SUCCESS = "GET_USER_BYID_SUCCESS";
export const GET_USER_ByID_FAILED = "GET_USER_ByID_FAILED";


export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";